version: '3.8'

services:
  backend:
    image: ghcr.io/${GH_REPO_OWNER}/backend:latest
    container_name: shop_backend
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PORT=8000
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - MONGODBATLAS=${MONGODBATLAS}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - VIETTELPOST_BASE_URL=${VIETTELPOST_BASE_URL}
      - VIETTELPOST_USERNAME=${VIETTELPOST_USERNAME}
      - VIETTELPOST_PASSWORD=${VIETTELPOST_PASSWORD}
      - SENDER_ADDRESS=${SENDER_ADDRESS}
      - VIETTELPOST_TOKEN=${VIETTELPOST_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # VNPAY SANDBOX CONFIG
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_URL=${VNPAY_URL}
      - VNPAY_API_URL=${VNPAY_API_URL}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
      # MOMO SANDBOX CONFIG
      - MOMO_PARTNER_CODE=${MOMO_PARTNER_CODE}
      - MOMO_ACCESS_KEY=${MOMO_ACCESS_KEY}
      - MOMO_SECRET_KEY=${MOMO_SECRET_KEY}
      - MOMO_API_URL=${MOMO_API_URL}
      - MOMO_REDIRECT_URL=${MOMO_REDIRECT_URL}
      - MOMO_IPN_URL=${MOMO_IPN_URL}
      # SEPAY CONFIG (QUẦY POS)
      - SEPAY_BANK_NAME=${SEPAY_BANK_NAME}
      - SEPAY_ACCOUNT_NO=${SEPAY_ACCOUNT_NO}
      - SEPAY_ACCOUNT_NAME=${SEPAY_ACCOUNT_NAME}
      - SEPAY_API_KEY=${SEPAY_API_KEY}
      - SEPAY_WEBHOOK_URL=${SEPAY_WEBHOOK_URL}
    ports:
      - "127.0.0.1:8000:8000"

  frontend_client:
    image: ghcr.io/${GH_REPO_OWNER}/frontend_client:latest
    container_name: shop_client
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.theluki.click/api
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

  frontend_admin:
    image: ghcr.io/${GH_REPO_OWNER}/frontend_admin:latest
    container_name: shop_admin
    restart: always
    environment:
      - VITE_API_URL=https://api.theluki.click/api
    ports:
      - "127.0.0.1:3001:80"
    depends_on:
      - backend
